const Languages = [
  { key: "af", value: "Afrikaans" },
  { key: "sq", value: "Albanian" },
  { key: "am", value: "Amharic" },
  { key: "ar", value: "Arabic" },
  { key: "hy", value: "Armenian" },
  { key: "as", value: "Assamese" },
  { key: "ay", value: "Aymara" },
  { key: "az", value: "Azerbaijani" },
  { key: "bm", value: "Bambara" },
  { key: "eu", value: "Basque" },
  { key: "be", value: "Belarusian" },
  { key: "bn", value: "Bengali" },
  { key: "bho", value: "Bhojpuri" },
  { key: "bs", value: "Bosnian" },
  { key: "bg", value: "Bulgarian" },
  { key: "ca", value: "Catalan" },
  { key: "ceb", value: "Cebuano" },
  { key: "zh-CN", value: "Chinese (Simplified)" },
  { key: "zh-TW", value: "Chinese (Traditional)" },
  { key: "co", value: "Corsican" },
  { key: "hr", value: "Croatian" },
  { key: "cs", value: "Czech" },
  { key: "da", value: "Danish" },
  { key: "dv", value: "Dhivehi" },
  { key: "doi", value: "Dogri" },
  { key: "nl", value: "Dutch" },
  { key: "en", value: "English" },
  { key: "eo", value: "Esperanto" },
  { key: "et", value: "Estonian" },
  { key: "ee", value: "Ewe" },
  { key: "fil", value: "Filipino (Tagalog)" },
  { key: "fi", value: "Finnish" },
  { key: "fr", value: "French" },
  { key: "fy", value: "Frisian" },
  { key: "gl", value: "Galician" },
  { key: "ka", value: "Georgian" },
  { key: "de", value: "German" },
  { key: "el", value: "Greek" },
  { key: "gn", value: "Guarani" },
  { key: "gu", value: "Gujarati" },
  { key: "ht", value: "Haitian Creole" },
  { key: "ha", value: "Hausa" },
  { key: "haw", value: "Hawaiian" },
  { key: "he", value: "Hebrew" },
  { key: "hi", value: "Hindi" },
  { key: "hmn", value: "Hmong" },
  { key: "hu", value: "Hungarian" },
  { key: "is", value: "Icelandic" },
  { key: "ig", value: "Igbo" },
  { key: "ilo", value: "Ilocano" },
  { key: "id", value: "Indonesian" },
  { key: "ga", value: "Irish" },
  { key: "it", value: "Italian" },
  { key: "ja", value: "Japanese" },
  { key: "jv", value: "Javanese" },
  { key: "kn", value: "Kannada" },
  { key: "kk", value: "Kazakh" },
  { key: "km", value: "Khmer" },
  { key: "rw", value: "Kinyarwanda" },
  { key: "gom", value: "Konkani" },
  { key: "ko", value: "Korean" },
  { key: "kri", value: "Krio" },
  { key: "ku", value: "Kurdish" },
  { key: "ckb", value: "Kurdish (Sorani)" },
  { key: "ky", value: "Kyrgyz" },
  { key: "lo", value: "Lao" },
  { key: "la", value: "Latin" },
  { key: "lv", value: "Latvian" },
  { key: "ln", value: "Lingala" },
  { key: "lt", value: "Lithuanian" },
  { key: "lg", value: "Luganda" },
  { key: "lb", value: "Luxembourgish" },
  { key: "mk", value: "Macedonian" },
  { key: "mai", value: "Maithili" },
  { key: "mg", value: "Malagasy" },
  { key: "ms", value: "Malay" },
  { key: "ml", value: "Malayalam" },
  { key: "mt", value: "Maltese" },
  { key: "mi", value: "Maori" },
  { key: "mr", value: "Marathi" },
  { key: "mni-Mtei", value: "Meiteilon (Manipuri)" },
  { key: "lus", value: "Mizo" },
  { key: "mn", value: "Mongolian" },
  { key: "my", value: "Myanmar (Burmese)" },
  { key: "ne", value: "Nepali" },
  { key: "no", value: "Norwegian" },
  { key: "ny", value: "Nyanja (Chichewa)" },
  { key: "or", value: "Odia (Oriya)" },
  { key: "om", value: "Oromo" },
  { key: "ps", value: "Pashto" },
  { key: "fa", value: "Persian" },
  { key: "pl", value: "Polish" },
  { key: "pt", value: "Portuguese" },
  { key: "pa", value: "Punjabi" },
  { key: "qu", value: "Quechua" },
  { key: "ro", value: "Romanian" },
  { key: "ru", value: "Russian" },
  { key: "sm", value: "Samoan" },
  { key: "sa", value: "Sanskrit" },
  { key: "gd", value: "Scots Gaelic" },
  { key: "nso", value: "Sepedi" },
  { key: "sr", value: "Serbian" },
  { key: "st", value: "Sesotho" },
  { key: "sn", value: "Shona" },
  { key: "sd", value: "Sindhi" },
  { key: "si", value: "Sinhala (Sinhalese)" },
  { key: "sk", value: "Slovak" },
  { key: "sl", value: "Slovenian" },
  { key: "so", value: "Somali" },
  { key: "es", value: "Spanish" },
  { key: "su", value: "Sundanese" },
  { key: "sw", value: "Swahili" },
  { key: "sv", value: "Swedish" },
  { key: "tl", value: "Tagalog (Filipino)" },
  { key: "tg", value: "Tajik" },
  { key: "ta", value: "Tamil" },
  { key: "tt", value: "Tatar" },
  { key: "te", value: "Telugu" },
  { key: "th", value: "Thai" },
  { key: "ti", value: "Tigrinya" },
  { key: "ts", value: "Tsonga" },
  { key: "tr", value: "Turkish" },
  { key: "tk", value: "Turkmen" },
  { key: "ak", value: "Twi (Akan)" },
  { key: "uk", value: "Ukrainian" },
  { key: "ur", value: "Urdu" },
  { key: "ug", value: "Uyghur" },
  { key: "uz", value: "Uzbek" },
  { key: "vi", value: "Vietnamese" },
  { key: "cy", value: "Welsh" },
  { key: "xh", value: "Xhosa" },
  { key: "yi", value: "Yiddish" },
  { key: "yo", value: "Yoruba" },
  { key: "zu", value: "Zulu" },
];

export default Languages;
